CREATE TABLE APPROVERS (
	GROUP_NAME VARCHAR(100) NOT NULL,
	APPROVER_NAME VARCHAR(100) NOT NULL,
  	CONSTRAINT GROUP_NAME_PK PRIMARY KEY(GROUP_NAME) USING 
    	INDEX  
    	TABLESPACE enrole_indexes
) TABLESPACE enrole_data;


INSERT INTO APPROVERS (GROUP_NAME, APPROVER_NAME) VALUES ('developer', 'Bill Sanderman');
INSERT INTO APPROVERS (GROUP_NAME, APPROVER_NAME) VALUES ('tester', 'Jill Vox');
